repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-case-conflict
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@3.0.3
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.48.0
    hooks:
      - id: eslint
        files: \.[jt]sx?$
        types: [file]
        args: [--cache, --fix]
        additional_dependencies:
          - "@vercel/style-guide@5.0.1"
          - eslint@8.48.0
          - eslint-plugin-react-refresh@0.4.3
          - eslint-plugin-simple-import-sort@10.0.0
          - eslint-plugin-tailwindcss@3.11.0
